### PR TITLE
Add simple_form datetime picker input class

### PR DESCRIPTION
**Pull request by r38y**
Hi there. This is the datetime picker input class I am using along with the stuff you have put together. People would need to add a require if they want the simple form input that way it just kind of sits there if they don't. 

I have no idea how to test this. Any ideas? How about how it's actually done? It is kind of custom to our current app.

### CODE REVIEW

**Comment by lubieniebieski** [comment]
I think we may use a very trivial app with `simple_form` gem, and just call something like:

``` haml

= simple_form_for @some_object do |f|
  = f.input :created_at, as: :datetime_picker
```

I think it the following code should a part of the gem as well, so user doesn't have to bother with adding more stuff to JS manifest file:

``` coffee
$ ->
  $("[data-behaviur~='datetime_picker']").datetimepicker()
```

**Comment by lubieniebieski** [comment]
anyway, high five for the idea! I think that the date-picker feature and the feature you've proposed will be used together in many cases, so it will be good to have them in one place

**Comment by lubieniebieski** [comment]
@r38y here's sample code: take a look and tell me what you think (it's far from perfect):

``` ruby
# app/inputs/base_picker.rb
class BasePicker < SimpleForm::Inputs::DateTimeInput

  def input
    timestamp = input_html_options[:value]
    if timestamp.blank?
      method_value = object.try(attribute_name)
      timestamp = template.l(method_value) if method_value # default value
    end

    #create the input

    datetime_input = @builder.text_field(attribute_name, { data: { format: @picker_format }, value: timestamp }.merge(input_html_options))

    # add calendar button

    calendar_icon = template.content_tag(:i, nil, {  class: "icon-calendar", data: { :"time-icon" => "icon-time", :"date-icon" => "icon-calendar"} })
    calendar_button = template.content_tag(:span, calendar_icon, { class: "add-on" })

    # add 'NOW' button to the input

    now_icon = template.content_tag(:i, nil, { class: "icon-check" })
    now_button = template.content_tag(:a, now_icon+"now", { class: "btn btn-now", data: { behaviour: "now-button"} })

    template.content_tag(:div, datetime_input + calendar_button + now_button, data: { behaviour: @picker_name }, class: "input-append date")
  end

end
```

``` ruby
# app/inputs/datetime_picker_input.rb
class DatetimePickerInput < BasePicker
  def input
    @picker_name = 'datetime_picker'
    @picker_format = "yyyy-MM-dd hh:mm"
    super
  end
end
```

``` ruby
# app/inputs/date_picker_input.rb
class DatePickerInput < BasePicker
  def input
    @picker_name = 'date_picker'
    @picker_format = "yyyy-MM-dd"
    super
  end
end
```

then just put `as: date_picker` when defining input

**Comment by rurounijones** [comment]
I do not see any value from Inheriting from DateTimeInput since they are totally different in terms of usage and we are overriding half the methods anyway in the BasePicker as as far as I can tell the label_target section is pointless.

Might as well inherit from the base. Not sure why we are adding the behaviour to the surrounding div as well as the input itself. Also the "now" button does nothing at the moment apart from display the button right? That functionality  needs to be added?

**Pull request closed without merging**
